import type { GameTemplate } from './types'

export const TEMPLATES: GameTemplate[] = [
  {
    id: 'tpl-birthday',
    slug: 'anniversaire',
    name: 'Anniversaire',
    emoji: '🎂',
    description: 'Célèbre avec style et découvre ce que tes amis pensent vraiment de toi',
    category: 'Célébration',
    color_from: '#f59e0b',
    color_to: '#ef4444',
    question_count: 8,
    questions: [
      'As-tu déjà fêté ton anniversaire sans le dire à personne ?',
      'Penses-tu que le fêté mérite un cadeau cette année ?',
      'As-tu déjà oublié l\'anniversaire de quelqu\'un dans ce groupe ?',
      'Penses-tu que le fêté a vieilli gracieusement ?',
      'As-tu déjà mangé le gâteau avant de le servir ?',
      'Penses-tu que le fêté est plus sage cette année ?',
      'As-tu déjà offert un cadeau recyclé ?',
      'Le fêté mérite-t-il une surprise ce soir ?',
    ],
  },
  {
    id: 'tpl-friends',
    slug: 'soiree-amis',
    name: 'Soirée entre amis',
    emoji: '🤣',
    description: 'Des questions hilarantes pour une soirée inoubliable',
    category: 'Soirée',
    color_from: '#8b5cf6',
    color_to: '#ec4899',
    question_count: 10,
    questions: [
      'As-tu déjà menti pour ne pas sortir avec des amis ?',
      'As-tu déjà eu un crush secret sur quelqu\'un dans ce groupe ?',
      'As-tu déjà volé de la nourriture dans le frigo d\'un ami ?',
      'As-tu déjà séché un cours ou le travail sans raison valable ?',
      'As-tu déjà envoyé un message à la mauvaise personne ?',
      'As-tu déjà fait semblant de ne pas voir quelqu\'un dans la rue ?',
      'As-tu déjà pleuré devant un film d\'animation ?',
      'As-tu déjà dit "j\'arrive dans 5 minutes" alors que tu n\'étais pas levé ?',
      'As-tu déjà mangé en secret pour ne pas partager ?',
      'As-tu déjà lu les messages de quelqu\'un sans lui dire ?',
    ],
  },
  {
    id: 'tpl-likely',
    slug: 'qui-est-le-plus',
    name: 'Qui est le plus…',
    emoji: '🕵️',
    description: 'Votez pour savoir qui dans le groupe est le plus susceptible de…',
    category: 'Votes',
    color_from: '#06b6d4',
    color_to: '#3b82f6',
    question_count: 8,
    questions: [
      'Penses-tu être la personne la plus drôle du groupe ?',
      'Penses-tu être la personne la plus courageuse du groupe ?',
      'Penses-tu être la personne qui mange le plus ?',
      'Penses-tu être la personne la plus romantique du groupe ?',
      'Penses-tu être le ou la plus organisé(e) du groupe ?',
      'Penses-tu être le ou la plus chaotique du groupe ?',
      'Penses-tu être la personne la plus aventurière ?',
      'Penses-tu être la personne la plus sage du groupe ?',
    ],
  },
  {
    id: 'tpl-hot',
    slug: 'questions-genantes',
    name: 'Questions gênantes',
    emoji: '🔥',
    description: 'Pour les groupes qui n\'ont peur de rien. Attention ça peut faire mal.',
    category: 'Osé',
    color_from: '#ef4444',
    color_to: '#f97316',
    question_count: 10,
    questions: [
      'As-tu déjà menti à un proche pour éviter une situation gênante ?',
      'As-tu déjà eu des sentiments pour un(e) ex de quelqu\'un du groupe ?',
      'As-tu déjà dit du mal d\'un ami dans son dos ?',
      'As-tu déjà eu envie de tout plaquer et disparaître ?',
      'As-tu déjà fouillé dans le téléphone de quelqu\'un sans permission ?',
      'As-tu déjà exagéré sur ton CV ou tes compétences ?',
      'As-tu déjà annulé des plans au dernier moment par flemme ?',
      'As-tu déjà regretté une relation amoureuse ?',
      'As-tu déjà menti sur ton âge ou ton statut ?',
      'As-tu déjà fait quelque chose dont tu n\'es pas fier(e) ?',
    ],
  },
  {
    id: 'tpl-students',
    slug: 'etudiants',
    name: 'Étudiants',
    emoji: '🎓',
    description: 'Parfait pour une promo, une coloc ou une soirée d\'intégration',
    category: 'Étudiant',
    color_from: '#10b981',
    color_to: '#06b6d4',
    question_count: 8,
    questions: [
      'As-tu déjà séché un cours magistral ?',
      'As-tu déjà rendu un devoir en retard ?',
      'As-tu déjà copié sur quelqu\'un lors d\'un examen ?',
      'As-tu déjà dormi en cours ?',
      'As-tu déjà travaillé la nuit avant un examen ?',
      'As-tu déjà mangé des pâtes 3 fois dans la même semaine ?',
      'As-tu déjà menti à tes parents sur tes notes ?',
      'Regrettes-tu ton choix d\'études (même un peu) ?',
    ],
  },
  {
    id: 'tpl-travel',
    slug: 'voyage',
    name: 'Voyage',
    emoji: '✈️',
    description: 'Pour animer un road trip, un séjour ou un voyage en groupe',
    category: 'Voyage',
    color_from: '#3b82f6',
    color_to: '#8b5cf6',
    question_count: 8,
    questions: [
      'As-tu déjà raté un avion ou un train ?',
      'As-tu déjà perdu tes bagages en voyage ?',
      'As-tu déjà voyagé sans réserver quoi que ce soit à l\'avance ?',
      'As-tu déjà mangé quelque chose de vraiment bizarre à l\'étranger ?',
      'Penses-tu être un bon compagnon de voyage ?',
      'As-tu déjà eu une aventure romantique lors d\'un voyage ?',
      'Peux-tu dormir n\'importe où (avion, bus, sol) ?',
      'As-tu déjà dépensé tout ton budget voyage en un jour ?',
    ],
  },
  {
    id: 'tpl-custom',
    slug: 'creation-libre',
    name: 'Création libre',
    emoji: '✏️',
    description: 'Crée ton propre jeu de A à Z avec tes propres questions',
    category: 'Custom',
    color_from: '#6366f1',
    color_to: '#a855f7',
    question_count: 0,
    questions: [],
  },
]

export function getTemplateBySlug(slug: string): GameTemplate | undefined {
  return TEMPLATES.find(t => t.slug === slug)
}
