import type { GameTemplate } from './types'

export const TEMPLATES: GameTemplate[] = [
  {
    id: 'tpl-confessions',
    slug: 'confessions',
    name: 'Confessions',
    emoji: '🤫',
    description: 'Ose avouer ce que tu n\'as jamais dit',
    category: 'Soirée',
    color_from: '#7c3aed',
    color_to: '#ec4899',
    question_count: 15,
    questions: [
      'As-tu déjà eu envie de coucher avec quelqu\'un dans ce groupe ?',
      'As-tu déjà envoyé un message sexuel à la mauvaise personne ?',
      'As-tu déjà fait semblant d\'avoir un orgasme ?',
      'As-tu déjà eu une aventure avec quelqu\'un en couple ?',
      'As-tu déjà regardé les photos intimes de quelqu\'un sans permission ?',
      'As-tu déjà eu des fantasmes sur quelqu\'un de ta famille éloignée ?',
      'As-tu déjà eu une relation sexuelle dans un lieu public ?',
      'As-tu déjà payé ou été payé pour quelque chose d\'intime ?',
      'As-tu déjà été dans un plan à trois ?',
      'As-tu déjà eu une relation avec quelqu\'un de beaucoup plus âgé que toi ?',
      'As-tu déjà utilisé quelqu\'un juste pour le sexe ?',
      'As-tu déjà trompé quelqu\'un que tu aimais vraiment ?',
      'As-tu déjà eu des sentiments pour un(e) ami(e) en couple ?',
      'As-tu déjà envoyé des photos intimes de toi ?',
      'As-tu déjà fait quelque chose d\'intime sous influence d\'alcool dont tu regrettes ?',
    ],
  },
  {
    id: 'tpl-tu-preferes',
    slug: 'tu-preferes',
    name: 'Tu préfères…',
    emoji: '🔥',
    description: 'Des choix impossibles qui révèlent tout',
    category: 'Soirée',
    color_from: '#ef4444',
    color_to: '#f97316',
    question_count: 15,
    questions: [
      'Tu préfères : sexe sans amour ou amour sans sexe ?',
      'Tu préfères : être trompé(e) et ne jamais le savoir ou le savoir et souffrir ?',
      'Tu préfères : coucher avec ton/ta meilleur(e) ami(e) ou avec l\'ex de ton/ta meilleur(e) ami(e) ?',
      'Tu préfères : une nuit torride avec un(e) inconnu(e) ou une relation longue mais ennuyeuse ?',
      'Tu préfères : que tout le monde sache tes fantasmes ou tes dettes ?',
      'Tu préfères : ne plus jamais avoir de sexe ou ne plus jamais tomber amoureux(se) ?',
      'Tu préfères : coucher avec quelqu\'un de très beau mais mauvais au lit ou l\'inverse ?',
      'Tu préfères : être infidèle une fois sans que ça se sache ou être accusé(e) sans l\'avoir fait ?',
      'Tu préfères : que ton/ta partenaire lise tous tes messages ou voie tout ton historique de navigation ?',
      'Tu préfères : une relation ouverte ou une relation exclusive avec quelqu\'un de jaloux ?',
      'Tu préfères : coucher avec ton patron(ne) pour une promotion ou rater ta carrière ?',
      'Tu préfères : que ton/ta ex soit heureux(se) sans toi ou malheureux(se) sans toi ?',
      'Tu préfères : sexe tous les jours avec quelqu\'un que tu n\'aimes pas ou une fois par an avec l\'amour de ta vie ?',
      'Tu préfères : que tes parents lisent tes messages ou voient tes photos ?',
      'Tu préfères : avoir un(e) partenaire trop collant(e) ou totalement indifférent(e) ?',
    ],
  },
  {
    id: 'tpl-hot-or-not',
    slug: 'hot-ou-pas',
    name: 'Chaud ou Froid',
    emoji: '🌡️',
    description: 'Tes limites révèlent qui tu es vraiment',
    category: 'Hot',
    color_from: '#dc2626',
    color_to: '#9333ea',
    question_count: 15,
    questions: [
      'As-tu déjà simulé quelque chose au lit pour faire plaisir ?',
      'As-tu déjà eu envie de quelqu\'un le soir de leur mariage ?',
      'As-tu déjà eu un plan sexuel que tu n\'assumes pas ?',
      'As-tu déjà menti sur ta vie sexuelle pour impressionner ?',
      'As-tu déjà continué à embrasser quelqu\'un alors que tu ne le/la trouvais plus attirant(e) ?',
      'As-tu déjà eu une attirance pour quelqu\'un du même genre que d\'habitude ?',
      'As-tu déjà regardé du contenu adulte en présence de quelqu\'un sans qu\'il/elle le sache ?',
      'As-tu déjà eu une conversation sexuelle avec quelqu\'un en dehors de ta relation ?',
      'As-tu déjà eu honte de quelque chose que tu aimes au lit ?',
      'As-tu déjà eu envie de coucher avec deux personnes du groupe en même temps ?',
      'As-tu déjà terminé une relation uniquement parce que le sexe était mauvais ?',
      'As-tu déjà fait quelque chose d\'intime pour rendre quelqu\'un jaloux ?',
      'As-tu déjà eu une relation sexuelle dans la voiture ?',
      'As-tu déjà flirté sérieusement avec quelqu\'un devant ton/ta partenaire ?',
      'As-tu déjà eu envie de tout recommencer avec un(e) ex uniquement pour le sexe ?',
    ],
  },
  {
    id: 'tpl-nuit-reverite',
    slug: 'nuit-de-verites',
    name: 'Nuit de vérités',
    emoji: '🌙',
    description: 'Les questions qu\'on ne pose jamais en soirée',
    category: 'Gênant',
    color_from: '#1d4ed8',
    color_to: '#7c3aed',
    question_count: 15,
    questions: [
      'As-tu déjà pleuré après une relation sexuelle ?',
      'As-tu déjà été vraiment amoureux(se) de quelqu\'un dans ce groupe ?',
      'As-tu déjà eu honte de la personne avec qui tu as couché ?',
      'As-tu déjà texté un(e) ex à 3h du matin ?',
      'As-tu déjà imaginé ta vie avec quelqu\'un du groupe ?',
      'As-tu déjà eu une relation sexuelle que tu ne devais absolument pas avoir ?',
      'As-tu déjà aimé quelqu\'un qui ne t\'a jamais aimé en retour ?',
      'As-tu déjà couché avec quelqu\'un pour oublier quelqu\'un d\'autre ?',
      'As-tu déjà menti à ton/ta partenaire sur ce que tu ressentais vraiment ?',
      'As-tu déjà regretté une relation qui te manque encore aujourd\'hui ?',
      'As-tu déjà eu envie de disparaître après une nuit avec quelqu\'un ?',
      'As-tu déjà répété "je t\'aime" sans le penser vraiment ?',
      'As-tu déjà eu une relation qui a tout détruit entre vous deux ?',
      'As-tu déjà choisi quelqu\'un par peur de la solitude ?',
      'As-tu déjà pardonné une infidélité et continué à en souffrir en silence ?',
    ],
  },
  {
    id: 'tpl-18plus',
    slug: 'interdit-moins-18',
    name: 'Interdit -18',
    emoji: '🔞',
    description: 'Réservé aux adultes. Âmes sensibles s\'abstenir.',
    category: 'Adulte',
    color_from: '#dc2626',
    color_to: '#7f1d1d',
    question_count: 15,
    questions: [
      'As-tu déjà eu des pensées intimes sur quelqu\'un dans ce groupe ?',
      'As-tu déjà eu une relation sexuelle filmée ou photographiée ?',
      'As-tu déjà payé ou été payé(e) pour une relation intime ?',
      'As-tu déjà eu plus de 10 partenaires sexuels ?',
      'As-tu déjà pratiqué quelque chose que tu jugeais tabou et que tu as finalement aimé ?',
      'As-tu déjà eu une relation avec quelqu\'un de la famille d\'un(e) ami(e) proche ?',
      'As-tu déjà fait quelque chose d\'intime sous l\'effet de substances ?',
      'As-tu déjà participé à un plan impliquant plus de deux personnes ?',
      'As-tu déjà eu des pratiques que tu n\'assumeras jamais publiquement ?',
      'As-tu déjà vécu une expérience intime que tu ne répèterais jamais ?',
      'As-tu déjà eu une attirance pour quelqu\'un d\'une relation "interdite" ?',
      'As-tu déjà utilisé des accessoires ou des jeux de rôle ?',
      'As-tu déjà couché avec quelqu\'un juste pour une revanche ?',
      'As-tu déjà eu une relation entièrement secrète pendant plusieurs mois ?',
      'As-tu déjà eu des sentiments pour quelqu\'un pendant une nuit et disparu le lendemain ?',
    ],
  },
  {
    id: 'tpl-custom',
    slug: 'creation-libre',
    name: 'Création libre',
    emoji: '✏️',
    description: 'Crée ton propre jeu avec tes propres questions',
    category: 'Custom',
    color_from: '#6366f1',
    color_to: '#a855f7',
    question_count: 0,
    questions: [],
  },
]

export function getTemplateBySlug(slug: string): GameTemplate | undefined {
  return TEMPLATES.find(t => t.slug === slug)
}
